
version: '3'

services:
  rabbitmq-service:
    image: eleott/rabbitmq_service:dev0ps7
    # container_name: rabbitmq-service
      
  postgres-service:
    container_name: postgres-service
    image: eleott/postgres_service:dev0ps7   
    # depends_on:
      # - rabbitmq-service
    # build: ./services/database
    # restart: always
    
    # restart: always
  
  gateway-service:
    # container_name: gateway-service
    # image: eleott/gateway_service:dev0ps7
    build: ./services/gateway-service
    # restart: always
    ports:
      - 8087:8087
    # depends_on:
    #   - postgres-service

  booking-service:
    # container_name: booking-service
    # image: eleott/booking_service:dev0ps7
    build: ./services/booking-service
    # restart: always
    # depends_on:
    #   - postgres-service
  
  hotel-service:
    # container_name: hotel-service
    # image: eleott/hotel_service:dev0ps7
    build: ./services/hotel-service
    # restart: always  
    # depends_on:
    #   - postgres-service
  
  loyalty-service:
    # container_name: loyalty-service
    # image: eleott/loyalty_service:dev0ps7
    build: ./services/loyalty-service
    # restart: always    
    # depends_on:
    #   - postgres-service
  
  payment-service:
    # container_name: payment-service
    # image: eleott/payment_service:dev0ps7
    build: ./services/payment-service
    # restart: always
    # depends_on:
    #   - postgres-service
  
  report-service:
    # container_name: report-service
    # image: eleott/report_service:dev0ps7
    build: ./services/report-service
    # restart: always
    # depends_on:
      # - postgres-service
  
  session-service:
    container_name: session-service
    # image: eleott/session_service:dev0ps7
    build: ./services/session-service
    # command: "java -jar session-service-0.0.1-SNAPSHOT.jar"
    # command: "tail -f /dev/null"
    # restart: always
    ports:
      - 8081:8081
    # depends_on:
      # - postgres-service
